name = "dc-bot"
main = "src/index.ts"
compatibility_date = "2026-01-14"

[observability]
[observability.logs]
enabled = false
invocation_logs = true

[vars]
# Public Variables
COMMAND_PREFIX = "/"
ENVIRONMENT = "production"
SUPPORT_SERVER = " "

# Secret Placeholders (Enter real values in Cloudflare Dashboard)
DISCORD_APPLICATION_ID = "PASTE_YOUR_ID_HERE"
DISCORD_PUBLIC_KEY = "PASTE_YOUR_PUBLIC_KEY_HERE"
DISCORD_TOKEN = "PASTE_YOUR_BOT_TOKEN_HERE"